class HttpResponseCode:
    HTTP_200_OK = 200
    HTTP_404_NOT_FOUND = 404
    HTTP_405_METHOD_NOT_ALLOWED = 405
    HTTP_500_INTERNAL_SERVER_ERROR = 500
    HTTP_403_FORBIDDEN = 403
    HTTP_304_NOT_MODIFIED = 304
    HTTP_408_REQUEST_TIMEOUT = 408
    HTTP_416_REQUESTED_RANGE_NOT_SATISFIABLE = 416
    HTTP_206_PARTIAL_CONTENT= 206

    HTTP_RESPONSE_MESSAGES = {
        HTTP_200_OK: "OK",
        HTTP_404_NOT_FOUND: "Not Found",
        HTTP_405_METHOD_NOT_ALLOWED: "Method Not Allowed",
        HTTP_500_INTERNAL_SERVER_ERROR: "Internal Server Error",
        HTTP_403_FORBIDDEN: "Forbidden",
        HTTP_304_NOT_MODIFIED: "Not Modified",
        HTTP_408_REQUEST_TIMEOUT: "Request Timeout",
        HTTP_416_REQUESTED_RANGE_NOT_SATISFIABLE: "Requested Range Not Satisfiable",
    }
